yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/create/', views.post_create, name='post_create'),
    path('posts/post_edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import *
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(template_name='users/password_change_form.html'),
        name='pass_change_view'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
        name='pass_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(template_name='users/password_reset_form.html'),
        name='pass_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='pass_reset_done'
    ),
    path(
        'reset/<uidb64>/token/',
        PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
        name='pass_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
        name='pass_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/about/models.py
from django.db import models

# Create your models here.

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(unique=True, verbose_name='Адрес')
    description = models.TextField(blank=False, verbose_name='Описание')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(blank=False, verbose_name='Описание')
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )

    def __str__(self):
        return self.text

yatube/posts/forms.py
from django.contrib.auth.forms import *
from .models import Post

class PostForm(Post.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)

yatube/users/forms.py
from django.contrib.auth.forms import *
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[
            'title'
        ] = 'Саша передаёт привет'
        return context


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Технологии'
        context[
            'text'
        ] = 'Гоблинская инженерия!'
        return context

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import PostForm
from .models import Group, Post

User = get_user_model()


def get_page_context(queryset, request):
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return {
        'paginator': paginator,
        'page_number': page_number,
        'page_obj': page_obj,
    }


def index(request):
    context = get_page_context(Post.objects.all(), request)
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    context.update(get_page_context(group.posts.all(), request))
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    context = {
        'author': author,
    }
    context.update(get_page_context(author.posts.all(), request))
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post': post,
    }
    context.update(get_page_context(post_id.posts.all(), request))
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.text = form.cleaned_data['text']
            post.group = form.cleaned_data['group']
            post.author = request.user
            post.save()
        return redirect(f'/profile/{request.user}/')
    else:
        form = PostForm()
    return render(request, template, {'form': form})


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post.text = form.cleaned_data['text']
            post.group = form.cleaned_data['group']
            post.author = request.user
            post.save()
            return redirect(f'/posts/{post_id}/')
        else:
            context = {
                'form': form,
                'is_edit': True
            }
        return render(request, template, context)
    else:
        if request.user == post.author:
            form = PostForm(instance=post)
            context = {
                'form': form,
                'is_edit': True
            }
            return render(request, template, context)

yatube/users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}

{% block title %} Об авторе проекта {% endblock %}

{% block content %}
<h1>Привет, я Саня</h1>
<p>
  Простите, я правда торопился
</p>
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}

{% block title %} Технологии {% endblock %}

{% block content %}
<div class="row">
  <h1>Вот что я умею</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>Ну привет. Неужели остальные разделы настолько скучные, что ты полез сюда?</p>
  </article>
</div>
{% endblock %}

yatube/templates/base.html
{% load static %}

<html lang="ru">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
        <link rel="apple-touch-icon"
              sizes="180x180"
              href="{% static 'img/fav/apple-touch-icon.png' %}">
        <link rel="icon"
              type="image/png"
              sizes="32x32"
              href="{% static 'img/fav/favicon-32x32.png' %}">
        <link rel="icon"
              type="image/png"
              sizes="16x16"
              href="{% static 'img/fav/favicon-16x16.png' %}">
        <meta name="msapplication-TileColor" content="#000">
        <meta name="theme-color" content="#ffffff">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <title>
            {% block title %} Контент {% endblock %}
        </title>
    </head>
    <body>
        {% include 'includes/header.html' %}
        <main>
            {% block content %} Контент {% endblock %}
        </main>
        {% include 'includes/footer.html' %}
    </body>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>
        © {{ year }} Copyright <span style="color:red">Ya</span>tube
    </p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <span style="color:red">Ya</span>tube
        </a>
        {% with request.resolver_match.view_name as view_name %}
        <ul class="nav nav-pills">
          <li class="nav-item"> 
            <a class="nav-link 
            {% if view_name  == 'about:author' %}
            active
            {% endif %}" 
            href="{% url 'about:author' %}">Об авторе</a>
          </li>
          <li class="nav-item">
            <a class="nav-link 
            {% if view_name  == 'about:tech' %}
            active
            {% endif %}" 
            href="{% url 'about:tech' %}">Технологии</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item"> 
            <a class="nav-link 
            {% if view_name  == 'posts:post_create' %}
            active
            {% endif %}" 
            href="{% url 'posts:create' %}">Новая запись</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link 
            {% if view_name  == 'users:password_change_form' %}
            active
            {% endif %}" 
            href="{% url 'users:password_change_form' %}">Изменить пароль</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link 
            {% if view_name  == 'users:logout' %}
            active
            {% endif %}" 
            href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li>
            Пользователь: {{ user.username }}
          </li>
          {% else %}
          <li class="nav-item"> 
            <a class="nav-link 
            {% if view_name  == 'users:login' %}
            active
            {% endif %}" 
            href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link 
            {% if view_name  == 'users:signup' %}
            active
            {% endif %}" 
            href="{% url 'users:signup' %}">Регистрация</a>
          </li>
          {% endif %}
        </ul>
        {% endwith %}
      </div>
    </nav>      
  </header>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %} Новая запись {% endblock %}

{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                Новый пост             
              </div>
              <div class="card-body">        
                <form method="post" action="../posts/create_post.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">            
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Group                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="" selected>---------</option>
                      <option value="1">Группа: Лев Толстой – зеркало русской революции</option>
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}               
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %} Записи сообщества {{group.title}} {% endblock %}

{% block content %}
    <div class="container py-5">
        <h1> Записи сообщества {{group.title}} </h1>
        <article>
            {% for post in posts %}
                <ul>
                    <li>Автор: {{ post.author.get_full_name }}</li>
                    <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
                </ul>
                <p>
                    {{ post.text }}
                </p>
                {% if not forloop.last %}<hr>{% endif %}
            {% endfor %}
        </article>
    </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %} Последние обновления на сайте {% endblock %}

{% block content %}
    <div class="container py-5">
        <h1> Последние обновления на сайте </h1>
        <article>
            {% for post in page_obj %}
                <ul>
                    <li>Автор: {{ post.author.get_full_name }}</li>
                    <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
                </ul>
                <p>
                    {{ post.text }}
                </p>
                {% if post.group %} 
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
                {% endif %} 
                {% if not forloop.last %}<hr>{% endif %}
            {% endfor %}
            {% include 'includes/paginator.html' %}
        </article>
    </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}

{% block title %} Детали поста {% endblock %}

{% block content %}
<html lang="ru">
  <head>  
    <!-- Подключены иконки, стили и заполенены мета теги -->
    <title>Пост <!-- Первые 30 букв поста --></title>
  </head>
  <body>
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: <!-- 31 июля 1854 --> 
            </li>
            <!-- если у поста есть группа -->   
              <li class="list-group-item">
                Группа: <!-- Название группы -->
                <a href="<!-- -->">
                  все записи группы
                </a>
              </li>
              <li class="list-group-item">
                Автор: <!--Лев Толстой-->
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span ><!-- --></span>
            </li>
            <li class="list-group-item">
              <a href="<!-- -->">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
           <!-- Толстовская ерунда --> 
          </p>
        </article>
      </div> 
    </main>
  </body>
</html>
{% endblock %}

yatube/templates/posts/post_edit.html
{% extends 'base.html' %}

{% block title %} Обновить запись {% endblock %}

{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                Редактировать пост             
              </div>
              <div class="card-body">        
                <form method="post" action="../posts/create_post.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">            
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">[Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ Монго. Человѣкъ пустой, но съ твердыми, хотя и ложными убѣжденіями. Генерал[у] по этому должно быть случаю, угодно было спрашивать о моемъ здоровьи. Свинья! К[о]вырялъ носъ и ничего не написалъ — вотъ 2 упрека за нын[ѣшній] день. Послѣдній упрекъ становится слишкомъ частъ, хотя походъ и можетъ служить въ немъ отчасти извиненіемъ. Отношенія мои съ товарищами становятся такъ пріятны, что мнѣ жалко бросить штабъ. Здоровье кажется (2) лучше.
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Group                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="">---------</option>
                      <option value="1" selected>Группа: Лев Толстой – зеркало русской революции</option>
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      Сохранить
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}

{% block title %} Профиль пользователя {% endblock %}

{% block content %}
<html lang="ru"> 
  <head>  
    <!-- Подключены иконки, стили и заполенены мета теги -->
    <title>Профайл пользователя <!--Лев Толстой--></title>
  </head>
  <body>
    <main>
      <div class="container py-5">        
        <h1>Все посты пользователя <!--Лев Толстой--> </h1>
        <h3>Всего постов: <!-- --> </h3>   
        <article>
          <ul>
            <li>
              Автор: <!--Лев Толстой-->
              <a href="<!-- -->">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: <!-- 31 июля 1854 --> 
            </li>
          </ul>
          <p>
          <!-- Толстовская ерунда --> 
          </p>
          <a href="<!-- -->">подробная информация </a>
        </article>       
        <a href="<!-- -->">все записи группы</a>        
        <hr>
        <!-- Остальные посты. после последнего нет черты -->
        <!-- Здесь подключён паджинатор -->
        {% include 'posts/includes/paginator.html' %}
      </div>
    </main>
  </body>
</html>
{% block content %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}

{% block title %} Вы вышли из системы {% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}

{% block title %} Войти {% endblock %}

{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:pass_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block title %} Пароль изменён {% endblock %}

{% block content %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Пароль изменён
              </div>
              <div class="card-body"> 
                <p>Пароль изменён успешно</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block title %} Смена пароля {% endblock %}

{% block content %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post" action="../users/password_change_form.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block title %} Пароль изменён {% endblock %}

{% block content %}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Восстановление пароля завершено
              </div>
              <div class="card-body">
                <p>Ваш пароль был сохранен. Используйте его для входа</p>
                <a href="../users/login.html">Войти</a>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
    </main>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}

{% block title %} Зарегистрироваться {% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
  </div>
{% endblock %}